name: Daily Issue Summary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 9h sáng GMT+7

jobs:
  issue-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get all issues
      id: get-issues
      run: |
        ISSUES=$(gh issue list --repo ${{ github.repository }} --json number,title,state,createdAt,updatedAt --jq '.[] | {number, title, state, createdAt, updatedAt}')
        echo "ISSUE_LIST=$ISSUES" >> $GITHUB_ENV

    - name: Send notification to Teams
      env:
        TEAMS_WEBHOOK
