name: Daily Issue Summary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 9h sáng GMT+7

jobs:
  issue-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI and jq
      run: |
        sudo apt-get update
        sudo apt-get install -y gh jq

    - name: Get all issues
      id: get-issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUES=$(gh issue list --repo ${{ github.repository }} --json number,title,state,createdAt,updatedAt)
        echo "Raw issues: $ISSUES"
        # Chuyển đổi JSON thành chuỗi đơn giản
        FORMATTED_ISSUES=$(echo "$ISSUES" | jq -r '.[] | "Issue #\(.number): \(.title) (\(.state)) - Created at \(.createdAt)"')
        echo "FORMATTED_ISSUES=$FORMATTED_ISSUES" >> $GITHUB_ENV

    - name: Verify FORMATTED_ISSUES content
      run: |
        echo "Formatted issues:"
        echo "${{ env.FORMATTED_ISSUES }}"
        if [ -z "${{ env.FORMATTED_ISSUES }}" ]; then
          echo "No issues found or formatted issues are empty"
          exit 1
        fi

    - name: Send notification to Teams
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        FORMATTED_ISSUES: ${{ env.FORMATTED_ISSUES }}
      run: |
        PAYLOAD=$(cat <<EOF
        {
          "@type": "MessageCard",
          "@context": "https://schema.org/extensions",
          "summary": "Daily GitHub Issue Summary",
          "themeColor": "0078D7",
          "title": "Daily Issue Summary",
          "sections": [
            {
              "activityTitle": "Summary of Issues",
              "facts": [
                {"name": "Repository", "value": "${{ github.repository }}"},
                {"name": "Generated At", "value": "$(date)"}
              ],
              "markdown": true
            },
            {
              "text": "${{ env.FORMATTED_ISSUES }}",
              "markdown": true
            }
          ]
        }
        EOF
        )
        curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"
